export const FETCH_MOVIEADMIN_REQUEST = "listMovieAdminReducer/FETCH_MOVIEADMIN_REQUEST";
export const FETCH_MOVIEADMIN_SUCCESS = "listMovieAdminReducer/FETCH_MOVIEADMIN_SUCCESS";
export const FETCH_MOVIEADMIN_FAILED = "listMovieAdminReducer/FETCH_MOVIEADMIN_FAILED";